# Generated by Django 2.2.7 on 2020-01-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobRequriment',
            new_name='jobHY',
        ),
    ]
