# Generated by Django 2.2.7 on 2020-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_jobdel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobNcr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
            ],
        ),
    ]
