# Generated by Django 2.2.7 on 2020-02-27 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
